"""
Mako template for Alembic revision scripts.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '079eca3e81a9'
down_revision = '2aba805c97dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually created Enums
    reviewer_role_enum = sa.Enum('primary', 'secondary', 'technical', 'editorial', 'manager', name='reviewer_role')
    review_assignment_status_enum = sa.Enum('pending', 'in_progress', 'completed', 'reassigned', name='review_assignment_status')
    comment_action_type_enum = sa.Enum('comment', 'ai_request', name='comment_action_type')

    # Alter existing doc_status enum if postgres
    connection = op.get_bind()
    if connection.dialect.name == 'postgresql':
        op.execute("ALTER TYPE doc_status ADD VALUE IF NOT EXISTS 'assigned'")
        op.execute("ALTER TYPE doc_status ADD VALUE IF NOT EXISTS 'needs_revision'")
        op.execute("ALTER TYPE doc_status ADD VALUE IF NOT EXISTS 'waiting_for_ai'")
        op.execute("ALTER TYPE doc_status ADD VALUE IF NOT EXISTS 'waiting_for_human'")
        op.execute("ALTER TYPE doc_status ADD VALUE IF NOT EXISTS 'ready_for_publish'")
        op.execute("ALTER TYPE doc_status ADD VALUE IF NOT EXISTS 'archived'")

    op.create_table('review_assignments',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('role', reviewer_role_enum, nullable=False),
    sa.Column('status', review_assignment_status_enum, nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.add_column('human_reviews', sa.Column('is_draft', sa.Boolean(), nullable=False))
    op.add_column('human_reviews', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('human_reviews', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('human_reviews', 'decision',
               existing_type=postgresql.ENUM('approved', 'needs_revision', 'rejected', name='review_decision_type'),
               nullable=True)
    op.alter_column('human_reviews', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('review_comments', sa.Column('document_id', sa.UUID(), nullable=False))
    op.add_column('review_comments', sa.Column('parent_comment_id', sa.UUID(), nullable=True))
    op.add_column('review_comments', sa.Column('action_type', comment_action_type_enum, nullable=False, server_default='comment'))
    op.add_column('review_comments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.alter_column('review_comments', 'human_review_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'review_comments', 'review_comments', ['parent_comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review_comments', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_comments', type_='foreignkey')
    op.drop_constraint(None, 'review_comments', type_='foreignkey')
    op.alter_column('review_comments', 'human_review_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('review_comments', 'updated_at')
    op.drop_column('review_comments', 'action_type')
    op.drop_column('review_comments', 'parent_comment_id')
    op.drop_column('review_comments', 'document_id')
    op.alter_column('human_reviews', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('human_reviews', 'decision',
               existing_type=postgresql.ENUM('approved', 'needs_revision', 'rejected', name='review_decision_type'),
               nullable=False)
    op.drop_column('human_reviews', 'updated_at')
    op.drop_column('human_reviews', 'created_at')
    op.drop_column('human_reviews', 'is_draft')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'owner_id')
    op.drop_table('review_assignments')
    
    # Drop manually created Enums
    sa.Enum('primary', 'secondary', 'technical', 'editorial', 'manager', name='reviewer_role').drop(op.get_bind(), checkfirst=True)
    sa.Enum('pending', 'in_progress', 'completed', 'reassigned', name='review_assignment_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum('comment', 'ai_request', name='comment_action_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
