"""
Mako template for Alembic revision scripts.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '079eca3e81a9'
down_revision = '2aba805c97dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    from sqlalchemy.dialects import postgresql
    
    from sqlalchemy.dialects import postgresql
    
    connection = op.get_bind()
    is_pg = connection.dialect.name == 'postgresql'
    
    if is_pg:
        op.execute("DROP TYPE IF EXISTS reviewer_role, review_assignment_status, comment_action_type CASCADE;")
        op.execute("CREATE TYPE reviewer_role AS ENUM ('primary', 'secondary', 'technical', 'editorial', 'manager');")
        op.execute("CREATE TYPE review_assignment_status AS ENUM ('pending', 'in_progress', 'completed', 'reassigned');")
        op.execute("CREATE TYPE comment_action_type AS ENUM ('comment', 'ai_request');")
        
        op.execute("ALTER TYPE doc_status ADD VALUE IF NOT EXISTS 'assigned'")
        op.execute("ALTER TYPE doc_status ADD VALUE IF NOT EXISTS 'needs_revision'")
        op.execute("ALTER TYPE doc_status ADD VALUE IF NOT EXISTS 'waiting_for_ai'")
        op.execute("ALTER TYPE doc_status ADD VALUE IF NOT EXISTS 'waiting_for_human'")
        op.execute("ALTER TYPE doc_status ADD VALUE IF NOT EXISTS 'ready_for_publish'")
        op.execute("ALTER TYPE doc_status ADD VALUE IF NOT EXISTS 'archived'")

        reviewer_role_type = postgresql.ENUM('primary', 'secondary', 'technical', 'editorial', 'manager', name='reviewer_role', create_type=False)
        review_assignment_status_type = postgresql.ENUM('pending', 'in_progress', 'completed', 'reassigned', name='review_assignment_status', create_type=False)
        comment_action_type = postgresql.ENUM('comment', 'ai_request', name='comment_action_type', create_type=False)
    else:
        reviewer_role_type = sa.Enum('primary', 'secondary', 'technical', 'editorial', 'manager', name='reviewer_role')
        review_assignment_status_type = sa.Enum('pending', 'in_progress', 'completed', 'reassigned', name='review_assignment_status')
        comment_action_type = sa.Enum('comment', 'ai_request', name='comment_action_type')
        
        reviewer_role_type.create(connection, checkfirst=True)
        review_assignment_status_type.create(connection, checkfirst=True)
        comment_action_type.create(connection, checkfirst=True)

    op.create_table('review_assignments',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('role', reviewer_role_type, nullable=False),
    sa.Column('status', review_assignment_status_type, nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.add_column('human_reviews', sa.Column('is_draft', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('human_reviews', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('human_reviews', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.alter_column('human_reviews', 'decision',
               existing_type=postgresql.ENUM('approved', 'needs_revision', 'rejected', name='review_decision_type'),
               nullable=True)
    op.alter_column('human_reviews', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('review_comments', sa.Column('document_id', sa.UUID(), nullable=False, server_default=sa.text("'00000000-0000-0000-0000-000000000000'")))
    op.add_column('review_comments', sa.Column('parent_comment_id', sa.UUID(), nullable=True))
    op.add_column('review_comments', sa.Column('action_type', comment_action_type, nullable=False, server_default='comment'))
    op.add_column('review_comments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.alter_column('review_comments', 'human_review_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'review_comments', 'review_comments', ['parent_comment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review_comments', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_comments', type_='foreignkey')
    op.drop_constraint(None, 'review_comments', type_='foreignkey')
    op.alter_column('review_comments', 'human_review_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('review_comments', 'updated_at')
    op.drop_column('review_comments', 'action_type')
    op.drop_column('review_comments', 'parent_comment_id')
    op.drop_column('review_comments', 'document_id')
    op.alter_column('human_reviews', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('human_reviews', 'decision',
               existing_type=postgresql.ENUM('approved', 'needs_revision', 'rejected', name='review_decision_type'),
               nullable=False)
    op.drop_column('human_reviews', 'updated_at')
    op.drop_column('human_reviews', 'created_at')
    op.drop_column('human_reviews', 'is_draft')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'owner_id')
    op.drop_table('review_assignments')
    
    # Drop manually created Enums
    sa.Enum('primary', 'secondary', 'technical', 'editorial', 'manager', name='reviewer_role').drop(op.get_bind(), checkfirst=True)
    sa.Enum('pending', 'in_progress', 'completed', 'reassigned', name='review_assignment_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum('comment', 'ai_request', name='comment_action_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
