"""
Mako template for Alembic revision scripts.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2047da58c067'
down_revision = 'c4c20028df9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iteration_history',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('stable_id', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('previous_content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('new_content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('context_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iteration_history_stable_id'), 'iteration_history', ['stable_id'], unique=False)
    op.add_column('document_blocks', sa.Column('stable_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_document_blocks_stable_id'), 'document_blocks', ['stable_id'], unique=False)
    op.add_column('document_sections', sa.Column('stable_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_document_sections_stable_id'), 'document_sections', ['stable_id'], unique=False)
    op.add_column('review_comments', sa.Column('node_stable_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_review_comments_node_stable_id'), 'review_comments', ['node_stable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_comments_node_stable_id'), table_name='review_comments')
    op.drop_column('review_comments', 'node_stable_id')
    op.drop_index(op.f('ix_document_sections_stable_id'), table_name='document_sections')
    op.drop_column('document_sections', 'stable_id')
    op.drop_index(op.f('ix_document_blocks_stable_id'), table_name='document_blocks')
    op.drop_column('document_blocks', 'stable_id')
    op.drop_index(op.f('ix_iteration_history_stable_id'), table_name='iteration_history')
    op.drop_table('iteration_history')
    # ### end Alembic commands ###
