"""
Mako template for Alembic revision scripts.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aba805c97dd'
down_revision = '2047da58c067'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually added ENUM creation for Postgres
    release_status_enum = sa.Enum('Draft', 'Internal_Review', 'Approved', 'Release_Candidate', 'Published', 'Archived', name='release_status')
    release_status_enum.create(op.get_bind(), checkfirst=True)
    
    # Manually add values to existing doc_change_type enum if in PostgreSQL
    connection = op.get_bind()
    if connection.dialect.name == 'postgresql':
        op.execute("ALTER TYPE doc_change_type ADD VALUE IF NOT EXISTS 'MERGE'")
        op.execute("ALTER TYPE doc_change_type ADD VALUE IF NOT EXISTS 'PUBLISH_RELEASE'")
        op.execute("ALTER TYPE doc_change_type ADD VALUE IF NOT EXISTS 'IMPORTED_VERSION'")
        op.execute("ALTER TYPE doc_change_type ADD VALUE IF NOT EXISTS 'RESTORE'")
        op.execute("ALTER TYPE doc_change_type ADD VALUE IF NOT EXISTS 'SYSTEM_UPDATE'")
        
    op.add_column('document_versions', sa.Column('actor_type', sa.String(), nullable=True))
    op.add_column('document_versions', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('document_versions', sa.Column('release_status', release_status_enum, nullable=False, server_default='Draft'))
    op.add_column('document_versions', sa.Column('checksum', sa.String(), nullable=True))
    op.add_column('document_versions', sa.Column('snapshot_canonical_url', sa.String(), nullable=True))
    op.add_column('document_versions', sa.Column('snapshot_html_url', sa.String(), nullable=True))
    op.add_column('document_versions', sa.Column('snapshot_markdown_url', sa.String(), nullable=True))
    op.add_column('document_versions', sa.Column('snapshot_pdf_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_versions', 'snapshot_pdf_url')
    op.drop_column('document_versions', 'snapshot_markdown_url')
    op.drop_column('document_versions', 'snapshot_html_url')
    op.drop_column('document_versions', 'snapshot_canonical_url')
    op.drop_column('document_versions', 'checksum')
    op.drop_column('document_versions', 'release_status')
    op.drop_column('document_versions', 'reason')
    op.drop_column('document_versions', 'actor_type')
    
    release_status_enum = sa.Enum('Draft', 'Internal_Review', 'Approved', 'Release_Candidate', 'Published', 'Archived', name='release_status')
    release_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
