"""
Mako template for Alembic revision scripts.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37ad88979457'
down_revision = '079eca3e81a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    is_pg = connection.dialect.name == 'postgresql'
    
    if is_pg:
        op.execute("DROP TYPE IF EXISTS editor_action_type CASCADE;")
        op.execute("CREATE TYPE editor_action_type AS ENUM ('AI', 'Human', 'System');")
        editor_action_type = postgresql.ENUM('AI', 'Human', 'System', name='editor_action_type', create_type=False)
    else:
        editor_action_type = sa.Enum('AI', 'Human', 'System', name='editor_action_type')
        editor_action_type.create(connection, checkfirst=True)

    op.create_table('node_locks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('node_stable_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_locks_node_stable_id'), 'node_locks', ['node_stable_id'], unique=False)
    op.create_table('node_edit_histories',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('node_stable_id', sa.String(), nullable=False),
    sa.Column('editor_id', sa.UUID(), nullable=True),
    sa.Column('edit_type', editor_action_type, nullable=False),
    sa.Column('old_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('new_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['editor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_edit_histories_node_stable_id'), 'node_edit_histories', ['node_stable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_edit_histories_node_stable_id'), table_name='node_edit_histories')
    op.drop_table('node_edit_histories')
    op.drop_index(op.f('ix_node_locks_node_stable_id'), table_name='node_locks')
    op.drop_table('node_locks')
    # ### end Alembic commands ###
