"""
Mako template for Alembic revision scripts.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7a4309b6544'
down_revision = 'edd500da59f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('generation_jobs', sa.Column('prompt', sa.String(), nullable=True))
    op.add_column('generation_jobs', sa.Column('report_type', sa.String(), nullable=True))
    op.add_column('generation_jobs', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('generation_jobs', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('generation_jobs', sa.Column('model', sa.String(), nullable=True))
    op.add_column('generation_jobs', sa.Column('token_usage', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('generation_jobs', sa.Column('artifacts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('generation_jobs', sa.Column('version', sa.String(), nullable=True))
    op.add_column('generation_jobs', sa.Column('errors', sa.String(), nullable=True))
    op.add_column('generation_jobs', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('generation_jobs', sa.Column('audit_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('generation_jobs', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('generation_jobs', sa.Column('duration', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'generation_jobs', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generation_jobs', type_='foreignkey')
    op.drop_column('generation_jobs', 'duration')
    op.drop_column('generation_jobs', 'created_by')
    op.drop_column('generation_jobs', 'audit_metadata')
    op.drop_column('generation_jobs', 'retry_count')
    op.drop_column('generation_jobs', 'errors')
    op.drop_column('generation_jobs', 'version')
    op.drop_column('generation_jobs', 'artifacts')
    op.drop_column('generation_jobs', 'token_usage')
    op.drop_column('generation_jobs', 'model')
    op.drop_column('generation_jobs', 'provider')
    op.drop_column('generation_jobs', 'priority')
    op.drop_column('generation_jobs', 'report_type')
    op.drop_column('generation_jobs', 'prompt')
    op.drop_column('generation_jobs', 'topic')
    # ### end Alembic commands ###
