"""
Mako template for Alembic revision scripts.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'edd500da59f5'
down_revision = '37ad88979457'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    is_pg = connection.dialect.name == 'postgresql'
    
    if is_pg:
        op.execute("DROP TYPE IF EXISTS ai_provider_type CASCADE;")
        op.execute("CREATE TYPE ai_provider_type AS ENUM ('groq', 'openai', 'anthropic', 'gemini', 'local');")
        ai_provider_type = postgresql.ENUM('groq', 'openai', 'anthropic', 'gemini', 'local', name='ai_provider_type', create_type=False)
        
        op.execute("DROP TYPE IF EXISTS proposal_status CASCADE;")
        op.execute("CREATE TYPE proposal_status AS ENUM ('pending', 'accepted', 'rejected', 'modified_accepted');")
        proposal_status = postgresql.ENUM('pending', 'accepted', 'rejected', 'modified_accepted', name='proposal_status', create_type=False)
    else:
        ai_provider_type = sa.Enum('groq', 'openai', 'anthropic', 'gemini', 'local', name='ai_provider_type')
        ai_provider_type.create(connection, checkfirst=True)
        
        proposal_status = sa.Enum('pending', 'accepted', 'rejected', 'modified_accepted', name='proposal_status')
        proposal_status.create(connection, checkfirst=True)

    op.create_table('ai_prompt_templates',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('template_text', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_prompt_templates_name'), 'ai_prompt_templates', ['name'], unique=True)
    op.create_table('ai_proposals',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('target_node_stable_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('context_bundle', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model_provider', ai_provider_type, nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('response_content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', proposal_status, nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['ai_prompt_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_proposals')
    op.drop_index(op.f('ix_ai_prompt_templates_name'), table_name='ai_prompt_templates')
    op.drop_table('ai_prompt_templates')
    # ### end Alembic commands ###
