"""
Mako template for Alembic revision scripts.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff1a29b50845'
down_revision = '746f85557906'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_context_caches',
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('context_package', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_index('ix_generation_context_caches_cache_key', 'generation_context_caches', ['cache_key'], unique=False)
    op.create_table('validation_policies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('min_authority', sa.Float(), nullable=False),
    sa.Column('min_freshness', sa.Float(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('max_duplicate_ratio', sa.Float(), nullable=False),
    sa.Column('min_sources', sa.Integer(), nullable=False),
    sa.Column('conflict_threshold', sa.Float(), nullable=False),
    sa.Column('knowledge_quality_threshold', sa.Float(), nullable=False),
    sa.Column('rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_validation_policies_is_active', 'validation_policies', ['is_active'], unique=False)
    op.create_index('ix_validation_policies_name', 'validation_policies', ['name'], unique=False)
    op.create_table('validation_audit_logs',
    sa.Column('validator_version', sa.String(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('knowledge_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('retrieved_chunks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('validation_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_validation_audit_logs_user_id', 'validation_audit_logs', ['user_id'], unique=False)
    op.create_table('generation_analytics',
    sa.Column('generation_job_id', sa.UUID(), nullable=True),
    sa.Column('collections_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('retrieved_documents_count', sa.Integer(), nullable=False),
    sa.Column('retrieved_chunks_count', sa.Integer(), nullable=False),
    sa.Column('context_size', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('retrieval_time_ms', sa.Integer(), nullable=False),
    sa.Column('validation_time_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_build_time_ms', sa.Integer(), nullable=False),
    sa.Column('generation_time_ms', sa.Integer(), nullable=False),
    sa.Column('knowledge_reuse_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('evidence_usage_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generation_analytics_generation_job_id', 'generation_analytics', ['generation_job_id'], unique=False)
    op.create_table('knowledge_snapshots',
    sa.Column('knowledge_version', sa.String(), nullable=False),
    sa.Column('collections_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('documents_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('chunks_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('embedding_version', sa.String(), nullable=False),
    sa.Column('validation_version', sa.String(), nullable=False),
    sa.Column('retrieval_session_id', sa.UUID(), nullable=True),
    sa.Column('configuration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('r2_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['retrieval_session_id'], ['retrieval_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_snapshots_retrieval_session_id', 'knowledge_snapshots', ['retrieval_session_id'], unique=False)
    op.create_table('validation_history',
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('validation_run_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_version', sa.String(), nullable=False),
    sa.Column('validation_policy_id', sa.UUID(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('conflict_count', sa.Integer(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['retrieval_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_policy_id'], ['validation_policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_validation_history_session_id', 'validation_history', ['session_id'], unique=False)
    op.create_index('ix_validation_history_validation_run_id', 'validation_history', ['validation_run_id'], unique=False)
    op.create_table('validation_reports',
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('knowledge_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('retrieved_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('validation_summary', sa.String(), nullable=True),
    sa.Column('authority_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('freshness_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confidence_scores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('conflicts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('duplicate_analysis', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('evidence_completeness', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('unsupported_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('recommendations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('r2_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['retrieval_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_validation_reports_session_id', 'validation_reports', ['session_id'], unique=False)
    op.create_table('evidence_attributions',
    sa.Column('generation_job_id', sa.UUID(), nullable=True),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('supporting_chunks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('supporting_documents', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('supporting_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('supporting_collections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('validation_report_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['knowledge_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validation_report_id'], ['validation_reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_attributions_generation_job_id', 'evidence_attributions', ['generation_job_id'], unique=False)
    op.create_index('ix_evidence_attributions_snapshot_id', 'evidence_attributions', ['snapshot_id'], unique=False)
    op.create_table('review_snapshots',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('knowledge_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('validation_report_id', sa.UUID(), nullable=True),
    sa.Column('ai_review_id', sa.UUID(), nullable=True),
    sa.Column('human_review_id', sa.UUID(), nullable=True),
    sa.Column('evidence_attribution_id', sa.UUID(), nullable=True),
    sa.Column('review_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('r2_path', sa.String(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ai_review_id'], ['ai_reviews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_attribution_id'], ['evidence_attributions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['human_review_id'], ['human_reviews.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_snapshot_id'], ['knowledge_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validation_report_id'], ['validation_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_snapshots_knowledge_snapshot_id', 'review_snapshots', ['knowledge_snapshot_id'], unique=False)
    op.create_index('ix_review_snapshots_version_id', 'review_snapshots', ['version_id'], unique=False)
    op.create_table('review_analytics',
    sa.Column('review_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('evidence_usage', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('citation_quality', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('unsupported_claims_count', sa.Integer(), nullable=False),
    sa.Column('conflicts_count', sa.Integer(), nullable=False),
    sa.Column('review_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['review_snapshot_id'], ['review_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_analytics_snapshot_id', 'review_analytics', ['review_snapshot_id'], unique=False)

    op.add_column('retrieval_sessions', sa.Column('request_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('retrieval_sessions', sa.Column('snapshot_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('retrieval_sessions', sa.Column('session_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retrieval_sessions', 'session_metadata')
    op.drop_column('retrieval_sessions', 'snapshot_metadata')
    op.drop_column('retrieval_sessions', 'request_metadata')

    op.drop_index('ix_review_analytics_snapshot_id', table_name='review_analytics')
    op.drop_table('review_analytics')
    op.drop_index('ix_review_snapshots_version_id', table_name='review_snapshots')
    op.drop_index('ix_review_snapshots_knowledge_snapshot_id', table_name='review_snapshots')
    op.drop_table('review_snapshots')
    op.drop_index('ix_evidence_attributions_snapshot_id', table_name='evidence_attributions')
    op.drop_index('ix_evidence_attributions_generation_job_id', table_name='evidence_attributions')
    op.drop_table('evidence_attributions')
    op.drop_index('ix_validation_reports_session_id', table_name='validation_reports')
    op.drop_table('validation_reports')
    op.drop_index('ix_validation_history_validation_run_id', table_name='validation_history')
    op.drop_index('ix_validation_history_session_id', table_name='validation_history')
    op.drop_table('validation_history')
    op.drop_index('ix_knowledge_snapshots_retrieval_session_id', table_name='knowledge_snapshots')
    op.drop_table('knowledge_snapshots')
    op.drop_index('ix_generation_analytics_generation_job_id', table_name='generation_analytics')
    op.drop_table('generation_analytics')
    op.drop_index('ix_validation_audit_logs_user_id', table_name='validation_audit_logs')
    op.drop_table('validation_audit_logs')
    op.drop_index('ix_validation_policies_name', table_name='validation_policies')
    op.drop_index('ix_validation_policies_is_active', table_name='validation_policies')
    op.drop_table('validation_policies')
    op.drop_index('ix_generation_context_caches_cache_key', table_name='generation_context_caches')
    op.drop_table('generation_context_caches')
    # ### end Alembic commands ###
