"""Diagnostic drafts, never reusable publication approvals.

The producer binds the rejected draft to inputs and exact original-source body
hashes. A future recovery protocol must reread those sources and rerun every
publication gate; this module does not implement or authorize automatic reuse.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
from pathlib import Path
from typing import Any

from .web_publication_contract import _report_narrative_text, _word_count


def fingerprint(value: Any) -> str:
    return hashlib.sha256(json.dumps(value, ensure_ascii=False, sort_keys=True,
                                     separators=(",", ":")).encode()).hexdigest()


class DraftCheckpoint:
    def __init__(self, path, *, inputs, sources, approved_evidence, storyline_plan):
        self.path = Path(path) if path is not None else None
        if self.path is None:
            self.data = {}
            return
        source_receipts = [
            {"url": source.url, "title": source.title, "source_type": source.source_type,
             "content_sha256": hashlib.sha256(source.content.encode()).hexdigest(),
             "metadata_sha256": fingerprint(source.metadata),
             "content_chars": len(source.content)}
            for source in sources
        ]
        context = {"inputs": inputs, "source_fingerprints": source_receipts,
                   "approved_evidence": approved_evidence, "storyline_plan": storyline_plan}
        context = json.loads(json.dumps(context, ensure_ascii=False))
        self.data = {
            "schema": "gen-rpt-diagnostic-draft-v1", "publication_authorized": False,
            "recovery_requires": ["reread_original_sources_and_match_hashes", "all_current_publication_gates"],
            "producer": {key: os.getenv(env, "") for key, env in (
                ("repository", "GITHUB_REPOSITORY"), ("run_id", "GITHUB_RUN_ID"),
                ("run_attempt", "GITHUB_RUN_ATTEMPT"), ("head_sha", "GITHUB_SHA"))},
            "context": context, "context_sha256": fingerprint(context), "events": [],
        }

    def record(self, phase, report, issues, *, revisions_used, error=None, budget=None):
        if self.path is None:
            return
        event = {"phase": phase, "revisions_used": revisions_used,
                 "quality_issues": list(issues), "error": error,
                 "report": report, "report_sha256": fingerprint(report),
                 "reader_visible_words": _word_count(_report_narrative_text(report)) if isinstance(report, dict) else 0}
        if budget is not None:
            event["length_budget"] = budget
        # Freeze each event before the caller mutates the next draft in place.
        self.data["events"].append(json.loads(json.dumps(event, ensure_ascii=False)))
        self.path.parent.mkdir(parents=True, exist_ok=True)
        temporary = self.path.with_suffix(self.path.suffix + ".tmp")
        temporary.write_text(json.dumps(self.data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        temporary.replace(self.path)
        # The raw checkpoint is runner-local only. Public Actions artifacts may
        # contain only this explicit hash/count projection, never arbitrary text
        # copied from inputs, sources, exceptions, or model-produced fields.
        diagnostic = self.path.with_suffix(".diagnostic.json")
        temporary = diagnostic.with_suffix(diagnostic.suffix + ".tmp")
        temporary.write_text(json.dumps(self.public_diagnostic(), indent=2) + "\n", encoding="utf-8")
        temporary.replace(diagnostic)

    def public_diagnostic(self):
        context = self.data["context"]
        events = []
        for event in self.data["events"]:
            item = {key: event[key] for key in
                    ("phase", "revisions_used", "report_sha256", "reader_visible_words")}
            item["quality_issues"] = [
                {"category": "total_word_count" if re.fullmatch(
                    r"The reader-visible decision brief needs 1,800-3,800 words; found \d+\.", str(issue))
                 else "quality_gate", "sha256": fingerprint(issue)}
                for issue in event["quality_issues"]
            ]
            item["error_sha256"] = fingerprint(event["error"]) if event["error"] is not None else None
            if "length_budget" in event:
                budget = event["length_budget"]
                item["length_budget"] = {key: budget[key] for key in (
                    "total_words", "protected_words", "fixed_words", "mutable_words",
                    "minimum_feasible_words", "mutable_capacity_words", "target_words")}
                item["length_budget"]["fields"] = [
                    # JSON paths are generated by the pipeline, but hashing them
                    # also keeps this projection safe if another producer uses it.
                    {"path_sha256": fingerprint(field["path"]),
                     **{key: field[key] for key in ("words", "min_words", "target_max_words", "mutable")}}
                    for field in budget["fields"]
                ]
            events.append(item)
        return {
            "schema": "gen-rpt-public-diagnostic-v1", "publication_authorized": False,
            "raw_draft_retained_in_artifact": False, "automatic_resume_supported": False,
            "producer": self.data["producer"], "context_sha256": self.data["context_sha256"],
            "inputs_sha256": fingerprint(context["inputs"]),
            "approved_evidence_sha256": fingerprint(context["approved_evidence"]),
            "storyline_plan_sha256": fingerprint(context["storyline_plan"]),
            "source_fingerprints": [
                {"source_sha256": fingerprint(source), "content_sha256": source["content_sha256"],
                 "metadata_sha256": source["metadata_sha256"],
                 "content_chars": source["content_chars"]}
                for source in context["source_fingerprints"]
            ],
            "events": events,
        }
